### ISSUE TITLE
Getting spawn error

### ISSUE THREAD

**Issue by jlin412** [JoanEsquivel/cypress-cucumber-boilerplate#3] opened 2022-08-31 17:43 UTC
`npm run cypress:execution`
Getting error
`Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:743:9)
    at afterRunHandler (/Users/jlair3/cypress-cucumber-api/node_modules/@badeball/cypress-cucumber-preprocessor/lib/add-cucumber-preprocessor-plugin.js:88:55)`
I am using node 18.
I didn't make any change yet but straight `npm i` and then `npm run cypress:execution`

**Comment by JoanEsquivel** [comment] 2022-08-31 23:28
Hello! I am not able to reproduce your issue. Can you check if you downloaded the Cucumber Json Formatter?

**Comment by JoanEsquivel** [comment] 2022-09-02 20:01
Closing it for now.

**Comment by JoanEsquivel** [comment] 2022-09-02 20:01
Closing it for now.

**Closed** 2022-09-02 20:01 UTC
Labels: question
